name: DebugBuild
on:
  push:
    branches:
      - master
env:
  # リポジトリのルートディレクトリを基点としたソリューションファイルパス
  solution_file_path: Engine/Engine.sln
  # Visual Staudioの構成(Debug / Release)
  CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          
      - name: Restore NuGet packages
        run: nuget restore ${{env.solution_file_path}}

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=X64,Configuration=${{env.CONFIGURATION}}
            
